version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/api
      - ./api/node_modules
    environment:
      - MONGODB_URL=mongodb://test:test@mongodb:27017
      - MONGODB_DATABASE=test
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test
volumes:
  mongo-volume: